Documentation:
  Enabled: false

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - Gemfile

Metrics/LineLength:
  Max: 120
  Exclude:
    - spec/**/*

Metrics/BlockLength:
  CountComments: false  # count full line comments?
  Max: 25
  ExcludedMethods:
    - describe
    - context
    - it
    - fake!

Metrics/MethodLength:
  Max: 15

# Offense count: 1
# Configuration parameters: ExpectMatchingDefinition, Regex, IgnoreExecutableScripts, AllowedAcronyms.
# AllowedAcronyms: CLI, DSL, ACL, API, ASCII, CPU, CSS, DNS, EOF, GUID, HTML, HTTP, HTTPS, ID, IP, JSON, LHS, QPS, RAM, RHS, RPC, SLA, SMTP, SQL, SSH, TCP, TLS, TTL, UDP, UI, UID, UUID, URI, URL, UTF8, VM, XML, XMPP, XSRF, XSS
Style/FileName:
  Exclude:
    - 'lib/artsy-eventservice.rb'

# Offense count: 2
# Configuration parameters: MinBodyLength.
Style/GuardClause:
  Exclude:
    - 'lib/artsy-eventservice/presenters/events/base_event.rb'